ci:
  autofix_prs: false
  autoupdate_schedule: quarterly

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: no-commit-to-branch
  - id: debug-statements
  - id: check-merge-conflict
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-shebang-scripts-are-executable
  - id: check-executables-have-shebangs
  - id: check-toml

- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v2.0.2
  hooks:
  - id: autopep8
    args: [--max-line-length=160]

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.255
  hooks:
  - id: ruff
    args: [--fix]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.7.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
