[tool.poetry]
name = "astro-plasma"
version = "0.1.0"
description = "A Cloudy database with functions to quickly interpolate physical state of astrophysical plasma without detailed Plasma modelling."
authors = ["Gurkirat Singh <tbhaxor@gmail.com>", "Alankar <alankardutta@iisc.ac.in>"]
license = "MIT"
readme = "README.md"
packages = [{include = "astro_plasma"}]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.1"
tqdm = "^4.64.1"
numpy = "^1.24.1"
h5py = "^3.7.0"
urllib3 = "^1.26.14"
python-dotenv = "^0.21.0"
mpi4py = "^3.1.4"
matplotlib = "^3.6.3"
colorama = "^0.4.6"
scipy = "1.9.3"


[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
